preprocessing:
  sampling_rate: 100
  filter:
    low_freq: 0.3
    high_freq: 35

model:
  input_shape: [3000, 7]
  batch_size: 32
  epochs: 100
  learning_rate: 0.0001
  optimizer:
    type: 'adam'
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 1e-07
  regularization:
    dropout_rate: 0.2
    l2: 0.0001 